### ISSUE TITLE
Error detected while processing function <SNR>118_close_cb_maple

### ISSUE THREAD

**Issue by arashm** [liuchengxu/vim-clap#204]
**Environment (please complete the following information):**
 - OS: Linux
 - (Neo)Vim version: 8.2.80
 - vim-clap version: master

**Describe the bug**
When maple is not compiled, the fuzzy search for files keeps generating errors.

```
Error detected while processing function <SNR>118_close_cb_maple:
line    3:
E906: not an open channel
Error detected while processing function <SNR>120_close_cb:
line    2:
E906: not an open channel
E906: not an open channel
```

**To Reproduce**
- If you have maple compiled, do `cargo clean`.
- Try doing `Clap files` and start searching.
- Errors keep showing while typing

**Expected behavior**
Should work I assume.

**screenshot**
![Peek 2020-01-03 01-04](https://user-images.githubusercontent.com/849640/71702028-19084100-2dc5-11ea-9231-874dd7421702.gif)

**Comment by liuchengxu** [comment]
`cargo clean` will remove the binary at `target/release/maple`. And you installed `maple` globally before, so the problem comes, for the global `maple` is not outdated, you can uninstall it via `cargo uninstall maple` or reinstall it globally via `cargo install --path . --force`.

I suggest you just to rerun `:call clap#helper#build_all()` to build the release binary locally as vim-clap will find the locally built binary first.

**Comment by arashm** [comment]
ah, that makes sense. thanks.
