### ISSUE TITLE
Improve the search algorithm

### ISSUE THREAD

**Issue by romgrk** [liuchengxu/vim-clap#257]
**Is your feature request related to a problem? Please describe.**
Improve the search algorithm.

**Describe the solution you'd like**
Use something more polished like [fzy](https://github.com/jhawthorn/fzy)'s algorithm. Match things even when there is no space in-between.

**Additional context**
Here is an example of an improvable result. Sequences at the start of a delimiter shoud match first. (Delimiter here is a path separator but could be a camelCase case switch).
![Screenshot from 2020-01-21 11-22-20](https://user-images.githubusercontent.com/1423607/72822740-9d214c00-3c40-11ea-9cb6-cccff9317612.png)

For comparison, the same search with fzy.
![Screenshot from 2020-01-21 11-23-43](https://user-images.githubusercontent.com/1423607/72822845-c5a94600-3c40-11ea-990c-f3735806987f.png)

If you're ok with this I can work on a PR.

**Comment by liuchengxu** [comment]
When the query contains space, clap use the [substring](https://github.com/liuchengxu/vim-clap/blob/c1a648182c/pythonx/clap/scorer.py#L202) algo, otherwise use the fzy algorithm. I guess the [Python](https://github.com/liuchengxu/vim-clap/blob/c1a648182c/pythonx/clap/scorer.py#L195) and [Rust implementation](https://github.com/liuchengxu/vim-clap/blob/master/pythonx/clap/extracted_fzy/src/lib.rs) of fzy algorightm is not exact with the c implementation. Feel free to open a PR if you find anything misaligned with the origin c implementation.

**Comment by romgrk** [comment]
That's strange, it's not the behavior I get. If there are no spaces in my query, Clap is still looking for the specific substring only.

The 2 queries below were made in the exact same directory:

![Screenshot from 2020-01-24 14-31-32](https://user-images.githubusercontent.com/1423607/73097929-52a90500-3eb6-11ea-802b-e9f3412a86cd.png)
![Screenshot from 2020-01-24 14-31-45](https://user-images.githubusercontent.com/1423607/73097930-52a90500-3eb6-11ea-81ab-663d2849e929.png)

Should I open an issue for this? Is there some configuration flags that could be modifying this? (no clap-specific configuration on my side)

**Comment by romgrk** [comment]
Fixed by upgrading to the latest version of vim-clap.
