### ISSUE TITLE
Filer first backspace removes two characters when using filer provider in Vim

### ISSUE THREAD

**Issue by arsiarola** [liuchengxu/vim-clap#306]
Open "Clap filer" type characters and press backspace, there will be 2 characters erased. This only happens for the first time that backspace is pressed.

This is especially annoying if you open filer and type single wrong character and press backspace since this will erase the character and move to the previous directory.

**Comment by liuchengxu** [comment]
Use neovim for now, the input of vim's popup is mocked and that's definitely brittle. I'm a neovim user, so not sure when I'll have time for this issue.

**Comment by arsiarola** [comment]
Ah okay, sorry that I didn't give more information but you realized it was only a vim problem.

**Comment by Grueslayer** [comment]
It seems you are really messing up with the input buffer here.

Let's assume you are entering `abc`. 
After that `s:cursor_idx=3` which seems valid.
Now pressing BS leading to `s:cursor_idx=2` which seems also valid **BUT** the input line now shows only `a`.

The cursor position has been moved one position but the input line decreased by two chars. 
After that BS works fine **BUT** that's because s:cursor_idx ist always one ahead:

After typing `bc` it shows (and filters) `abc`
The `s:cursor_idx=4` which is wrong.

That all starts with:
```vim
function! s:bs_action() abort
  call clap#highlight#clear()

  let input = g:clap.input.get()
  if input ==# ''
    call s:goto_parent()
  else
    call g:clap.input.set(input[:-2])
    call s:filter_or_send_message()
  endif
  return ''
endfunction
```
This function is written having in mind, that the buffer is still unchanged and containing all characters, in this example `abc`.
But the last letter `c` has been already stripped off by `s:backspace` called in

```vim
function! s:move_manager.bs(_winid) abort
  call s:backspace()
  if has_key(g:clap.provider._(), 'bs_action')
    call s:mock_input()
    call g:clap.provider._().bs_action()
  else
    call s:apply_on_typed()
  endif
endfunction
```
so you additionally strip off one more character by calling input.set (which is wrong, cause it already was removed) and input.set does not change the s:cursor_indx to the given new text (which is also wrong),

Or did I missed something?

**Comment by liuchengxu** [comment]
@Grueslayer Looks reasonable at the first glance. Mind sending a PR?

**Comment by Grueslayer** [comment]
This isn't a VIM problem at all. It still exists in nvim, the result is a little different.

- in VIM it is like described: two characters are deleted, cursor_idx decreased only by one (cursor not visible in vim). Every addition character is appended at the end of the string.
- in NVIM only one character is removed, the cursor_idx possible not decreased (not verified) BUT the visible cursor still is at the previous position, so writing another character it is appended with space before. Pressing `abc`, than BS, and `d` leads to `abc d`.

The reason is like described from me before. You need to 
- do not call backspace() if there is an handler subscribed (or determine by a return value from handler to do it afterwards)
- or give the handler both (before and after) so you know if you pressed BS on an empty string (go parent) or the BS leads to an empty string (do nothing)

**Comment by liuchengxu** [comment]
>in NVIM only one character is removed, the cursor_idx possible not decreased (not verified) BUT the visible cursor still is at the previous position, so writing another character it is appended with space before. Pressing abc, than BS, and d leads to abc d.

This should be incorrect and I can not reproduce it with neovim. Neovim does not have this problem as it's focusable and you don't have to handle the cursor movment manually.

**Comment by liuchengxu** [comment]
Based on your suggestion, this patch seems to work:

```diff
diff --git a/autoload/clap/popup/move_manager.vim b/autoload/clap/popup/move_manager.vim
index 2073c5e..33493d7 100644
--- a/autoload/clap/popup/move_manager.vim
+++ b/autoload/clap/popup/move_manager.vim
@@ -90,10 +90,11 @@ function! s:backspace() abort
 endfunction

 function! s:move_manager.bs(_winid) abort
+  let before_bs = s:strpart_input(0, s:cursor_idx).s:strpart_input(s:cursor_idx)
   call s:backspace()
   if has_key(g:clap.provider._(), 'bs_action')
     call s:mock_input()
-    call g:clap.provider._().bs_action()
+    call g:clap.provider._().bs_action(before_bs)
   else
     call s:apply_on_typed()
   endif
diff --git a/autoload/clap/provider/filer.vim b/autoload/clap/provider/filer.vim
index ffdb2e4..3e2cf5d 100644
--- a/autoload/clap/provider/filer.vim
+++ b/autoload/clap/provider/filer.vim
@@ -89,14 +89,14 @@ function! s:filter_or_send_message() abort
   endif
 endfunction

-function! s:bs_action() abort
+function! s:bs_action(before_bs) abort
   call clap#highlight#clear()

   let input = g:clap.input.get()
-  if input ==# ''
+  if a:before_bs ==# ''
     call s:goto_parent()
   else
-    call g:clap.input.set(input[:-2])
+    " call g:clap.input.set(input[:-2])
     call s:filter_or_send_message()
   endif
   return ''
```

**Comment by Grueslayer** [comment]
Hi, this seems to work on VIM in the first tests but nvim didnt work anymore. You need also to change the call in autoload/clap/handler.vim to supply the additional paramater.

**Comment by liuchengxu** [comment]
Great, here is the complete patch. Feel free to review. @Grueslayer

**Comment by Grueslayer** [comment]
Please don't get me wrong, I am really happy for your plugin and fixing things. Maybe I am a liitle to bit on the academic side  but I think your solution isn't a good one:

- now we've two interface signatures for the same function
- provider programmers (which must not only be you) need to implement something for nvim and another for vim (leading possible to providers running only for one system)
- provider programmers need to know about the inner implementation (which should be hidden)
- nvim provider can change anything in the input, like `abc()` -> `abc`: deleting pairs when pressing BS, vim provider only handles BS outside the provider and need to run with the result.

I haven't taken a look in the source but as I understand our conversation:

- nvim has a function which handles key input for you. `handler.vim` is your callback for this. if the provider does not register for `bs_action` you handle the BS otherwise the provider sets the current input like it thinks it should be.
- vim hasn't such a function, you immitate it by `move_manager.vim`. 

In my opinion vim should behave exact the same way, so move_manager.vim should call the provider, provider should set the new input. So setting the new input must lead to a change in the internal buffer from move_manager (like it does in nvim's internal handling). As you wrote there is a problem with multi-byte-support (I am no chinese/japan/korean user, so I really only know what is is technical not how to program or use such keystrokes / characters). Isn't it possible to convert to input buffer from provider (which is handles as real characters) to their responsible multi-byte represantation in the move_manager (you already must done this in the other way).

If it would be possible we can have a clean interface and keep trouble from provider implementors away.

Please don't feel attacked! Just my opionion. 

Again, thank you for this.

**Comment by liuchengxu** [comment]
That's totaly fine. I also don't like the way of having two different signature for neovim and vim, but it's the most simple and practical way to fix the problems people are trapped in, at least it works now. I'm happy to accept a patch that proposes a more elegant solution.

As I mentioned in https://github.com/vim/vim/issues/5639, the root cause is that vim's popup is not like neovim's floating win which is focuable, each plugin like vim-clap has to mock the input display in a dirty way, facing the multi-byte issue like https://github.com/liuchengxu/vim-clap/pull/320 directly.

**Comment by Grueslayer** [comment]
Had a look into the code and don't see what makes nvim / vim in case of multi-byte different.

Both use `encoding` for representation of the internal strings, Lets go for German umlauts (because thats my mothers tounge):

For VIM
```vim
set encoding=iso-8859-1
echo len('Umlaut Ä')
```
gives you 8 because Ä is part of the Latin 1 (iso-8859-1) codepage.

```vim
set encoding=utf-8
echo len('Umlaut Ä')
```
will give you 9, because Ä is represented by 2 bytes (and I think this behaves like Chineese which may become 3 bytes in UTF-8).

nvim is completly on the same side, it is ALWAYS on codepage=utf-8.
In your current implementation of `filer.vim` you will have the same problem on nvim, you can not remove a character by byte-array access:

```vim
      call g:clap.input.set(input[:-2])   
```

For my example

```vim
echo 'Umlaut Ä'[:-2]
echo len('Umlaut Ä'[:-2])
```
shows you
```
Umlaut <c3>
8
```

So you must have in vim *AND* nvim the multibyte utf-8 encoding in mind.

**Comment by liuchengxu** [comment]
Yeah, I can't deny that there also might be some coner issues about the multi-byte in the other places.

But for neovim, I at least don't have to worry about displaying the user input and the cursor movement. For vim, you have to handle them manully. If vim can support the focuable popup like neovim, then we no longer need https://github.com/liuchengxu/vim-clap/blob/master/autoload/clap/popup/move_manager.vim, I'm really not a fan of it.

For the specific issue you just found, this patch might be helpful:

```diff
diff --git a/autoload/clap/provider/filer.vim b/autoload/clap/provider/filer.vim
index 75e0ffe..2680e09 100644
--- a/autoload/clap/provider/filer.vim
+++ b/autoload/clap/provider/filer.vim
@@ -90,7 +90,8 @@ if has('nvim')
     if input ==# ''
       call s:goto_parent()
     else
-      call g:clap.input.set(input[:-2])
+      " call g:clap.input.set(input[:-2])
+      call nvim_feedkeys("\<BS>", 'n', v:true)
       call s:filter_or_send_message()
     endif
     return ''
```

Just let neovim handle these stuffs.
