### ISSUE TITLE
Use pregenerated tag files

### ISSUE THREAD

**Issue by macthecadillac** [liuchengxu/vim-clap#446]
**Is your feature request related to a problem? Please describe.**
Ctags doesn't work well out of the box with Rust/Haskell/possibly many other languages. There are tools to generate these tag files (I have a plugin myself to handle the tools automatically on write), and Vim/Neovim is able to read them with the `tag` command. However, clap doesn't seem to know to use them instead.

**Describe the solution you'd like**
Add a provider for searching preexisting tag files. For example, that provider should search the project root/current directory for tag files.

**Comment by liuchengxu** [comment]
`:Clap tags` and `:Clap proj_tags` works out of the box for me with Rust using the universal-ctags. You can extend the current `tags` provider by searching the tag files instead of using the API of vista.vim only.

**Comment by macthecadillac** [comment]
That's weird. For me `Clap proj_tags` only works with rust when my project also has python code in it. I'll look into the tags provider once I have some time on hand.

**Comment by ray-x** [comment]
For me. proj_tags does not work out of box if I use default universal ctags come from `brew install --HEAD universal-ctags/universal-ctags/universal-ctags`. Because `ctags --outpout-format=json` not support by ctags by default. 
Will need to install jasson lib (with brew) and compile the source to enable json output.

**Comment by liuchengxu** [comment]
@ray-x Not an issue for me, and it's utterly easy to reinstall ctags with json support https://github.com/liuchengxu/vista.vim#compile-ctags-with-json-format-support.

**Comment by hasufell** [comment]
I can't see from the comments how to fix this. Haskell definitely doesn't work out of the box and needs [hasktags](https://github.com/MarcWeber/hasktags).

**Comment by liuchengxu** [comment]
@hasufell Well, I don't write Haskell, and if ctags doesn't support Haskell, then it indeed won't work. But if you are using vista.vim and have configured it properly, at least `:Clap tags` should work as `tags` provider uses the API of vista.vim. Not sure if codex has the same json format of ctags, otherwise a new parser should be created for codex specically. Currently `proj_tags` is actually handled in https://github.com/liuchengxu/vim-clap/blob/master/crates/maple_cli/src/cmd/tags.rs .

**Comment by hasufell** [comment]
Codex is about project tags, not buffer tags and is an expensive operation to run, since it includes tags of dependencies. The proper solution is to support an external tags file that the user manages.

**Comment by liuchengxu** [comment]
Each tag file may have its own format, so it's not easy to find a general tags file solution. You can try to write a new clap provider to parse the tag file generated by codex.

Resources for writing a clap provider:

-  https://github.com/liuchengxu/vim-clap/wiki/Examples
- https://github.com/liuchengxu/vim-clap/blob/master/PROVIDER.md
- https://github.com/liuchengxu/vim-clap/tree/master/autoload/clap/provider

**Comment by hasufell** [comment]
https://github.com/MarcWeber/hasktags/issues/69 doesn't currently support json

**Comment by romgrk** [comment]
> Each tag file may have its own format, so it's not easy to find a general tags file solution. 

Actually tag files are pretty standard. They all use the format generated by the original ctags tool, tab-separated fields in this order: _tag name_, _file_, _ex-command_, _kind_, _attributes_. They are so standard that as long as you configure the vim options `'tags'` correctly, you can simply use the `:tag my_tag_name` command to let vim take you to your tag.

I also agree that the project tags provider should be improved to play nice with any pre-generated tagfiles. Meanwhile you can use the following snippet to use your pre-generated tagfiles:

```viml
let clap_provider_generated_tags = {
\ 'source': {-> Tags__source()},
\ 'sink': {line -> Tags__sink(line)},
\}

function! Tags__source ()
  return flatten(map(tagfiles(), {_, file -> filter(readfile(file), 'stridx(v:val, "!_TAG") != 0')}))
endfunc

function! Tags__sink (line)
  " Let vim handle the tag
  execute 'tag' split(a:line, '\t')[0]
endfunc

```

**Comment by liuchengxu** [comment]
>Actually tag files are pretty standard. They all use the format generated by the original ctags tool, tab-separated fields in this order: tag name, file, ex-command, kind, attributes. They are so standard that as long as you configure the vim options 'tags' correctly, you can simply use the :tag my_tag_name command to let vim take you to your tag.

If so, that would be easier. What we need to figure out is how to search for these standard tag files. If found any, we can just read them instead of generating the tags again. I usually don't use this way, so not familiar with the way of find these tag files.

**Comment by romgrk** [comment]
> If so, that would be easier. What we need to figure out is how to search for these standard tag files. If found any, we can just read them instead of generating the tags again. I usually don't use this way, so not familiar with the way of find these tag files.

This is very very easy in vim: `:h tagfiles()` will return the list of available tag files.
The tagfiles are searched in the path in the `:set tags` options. It's a list of places to search the tagfiles with the same format as `:set path`. The default value works just fine: `:set tags=./tags;,tags` will find files named `tags` at the base of CWD or any parent up to `/` I think. But as I said `tagfiles()` does this for you, just need to call it.

This is a good summary of the ctags format: http://ctags.sourceforge.net/FORMAT
But as I described above, you basically just take the first 3 tab-delimited fields of each line and you're good to go.

The only problem with tag files is that they can get very big, and I tried implemented something with vimscript but it's too slow to read & render lines from a file with thousands of entries, so a proper solution would need to use rust/maple and use caching as much as possible.

I had also one question: is it currently possible for sources to provide different input for searching and for rendering? I was thinking that feeding tag lines directly into the filtering isn't ideal because it matches the tagName and the sourceFile, however when I search for tags I only want the tagName to be searched, but having the sourceFile displayed is nice and essential sometimes.

Something like this:
```
╭────────────────────────────────────────────────────────╮
│> mytagname                                             │
├────────────────────────────────────────────────────────┤
│MyTagName                                  src/my_file.c│
│my_tag_name                             src/other_file.c│
│my_tag_name2                            src/other_file.c│
│                                                        │
╰────────────────────────────────────────────────────────╯
```

**Comment by liuchengxu** [comment]
Yeah, if the performance is bad in vimscript, you can try to implement the core logic in Rust. You can pass the path of tagfiles and query string to `maple`, after tagfiles are processed, send back the final rendered lines, basically you can do anything on the Rust side, including your own special filtering.

**Comment by hasufell** [comment]
@romgrk your snippet from above works. That's cool. A few things I noticed:

1. I can confirm it's rather slow with a 30mb tags file
2. links in my tags file are absolute filepaths, so the output is hard to read (we had this discussion elsewhere about truncation behavior, I believe this needs to be smarter)
3. it searches the whole string, including the filepath

**Comment by romgrk** [comment]
@hasufell I just opened https://github.com/liuchengxu/vim-clap/pull/557 to address those concerns, it implements a proper tagfiles provider.

1. Should be handled correctly, if you want to test that PR go ahead
2. Will check to handle paths better
3. On my task list

**Comment by liuchengxu** [comment]
I realize that it's likely easier to extend the `dumb_jump` provider with tags file support. And I found an interesting project https://github.com/universal-ctags/citre which is an Emacs plugin on the power of ctags, one feature of which is that it supports tag finding and jumping via `readtags` which has a good performance due to it searches the tags file using binary search. 

So the concrete task is either to translate the C implementation of `readtags` https://github.com/universal-ctags/libreadtags/blob/master/readtags.c to Rust or to make use of `readtags` in maple using the CLI interface.

**Comment by liuchengxu** [comment]
This is resolved in the latest `dumb_jump` provider to some extent. That being said, `dumb_jump` does not search the existing external tags file, but tries to manage the tags files on its own. Apart from `ctags`, `gtags` is also supported in `dumb_jump`(#792). When you invoke the `dumb_jump` provider via `:Clap dumb_jump`, it will check if the tags and GTAGS file already exists for the current project, if yes, try to update, if not, generate them. Specifically, always recreate the tags file of `ctags` because it's much faster, incrementally update the GTAGSfile since gtags supports that. All these tags files are stored in one place(e.g, ` ~/.local/share/vimclap/tags` and ` ~/.local/share/vimclap/gtags`) so that they don't pollute the current directory. Generally speaking, the current `dumb_jump` is more advanced than just reading the existing external tags files.

**Comment by hasufell** [comment]
I don't understand from your explanation whether this allows custom tagfile producers. Neither ctags nor gtags works for me. I'm using a custom binary that generates these: https://hackage.haskell.org/package/codex

**Comment by liuchengxu** [comment]
Well, only ctags and gtags are supported for `dumb_jump` provider, so the answer is no. A dedicated provider for your use case seems to be necessary indeed where you specify the path for searching the tags files and then parse them.

**Comment by liuchengxu** [comment]
@hasufell @macthecadillac Feel free to try #944
