### ISSUE TITLE
Allow calling `files` or `grep` provider for specific directory

### ISSUE THREAD

**Issue by gavynriebau** [liuchengxu/vim-clap#47]
I'd like to be able to specify which directory is searched using an argument to the `files` or `grep` providers.
e.g. something along the lines of:
`Clap files app/` - search a specific directory
`Clap files .` - search the current directory
`Clap files ..` - search the parent directory

This would be particularly useful when you have a file open and want to open another file known to be in the same directory.

The same feature was already requested in [a comment against issue 6](https://github.com/liuchengxu/vim-clap/issues/6#issuecomment-540307363).

**Comment by joefiorini** [comment]
I'd like to see this as well. The one extremely useful shortcut I'm still missing from my old Spacemacs setup is `<Space>saf` to search in the directory of the file in the current buffer. I've tried to implement this myself in "userland" by using a custom `:command!` but I don't think it's possible since all the most popular `grep`-like tools take the query first _then_ the directory. I've checked and can't find an argument I can pass before the query to limit the search to a particular directory (this would make it completely possible in userland).

One way I've thought we could fix this is to allow a token in the grep args global like `%q` that would get replaced with the typed query at runtime. Then I could implement something like:

```viml
function! FindInFolder(folder)
  let orig = g:clap_provider_grep_opts
  let g:clap_provider_grep_opts = "%q " . a:folder
  " Is this sync or async? Do I need to somehow wait for it to close to have it reset?
  exec "Clap grep"
  let g:clap_provider_grep_opts = orig
endfunction

:command FindInCurrentBufferFolder call FindInFolder(expand("%:h"))
```

There may be an easier way to implement the above, but if we could have a token like that it would help implement this. Another option might be to use a lambda or function reference that receives the query and customizes the command line string.

Thoughts?

**Comment by liuchengxu** [comment]
>is it possible to create a new provider by extending a provider and overriding the command?

The most easy way is to modify `autoload/clap/provider/grep.vim` locally to satisfy your need until this issue is resolved. I accept PR if the modification is also helpful for others,

**Comment by gavynriebau** [comment]
Thank you @liuchengxu, love your work! 😄

**Comment by joefiorini** [comment]
Thanks! This looks awesome, can’t wait to give it a try!
