### ISSUE TITLE
Filer: Callstack while entering directory twice

### ISSUE THREAD

**Issue by Grueslayer** [liuchengxu/vim-clap#501]
If you 

1. open filer `Clap filer` in any directory
2. move with cursor to any subdir
3. change directory with TAB
4. go back with BS
5. move to the same directory with cursor
6. reenter directory with TAB

you'll see instead of the files a callstack with vim error:

```
provider.on_typed:
function clap#popup#move_manager#filter[3] 
..<lambda>12[1]
..clap#handler#tab_action[2]
..<SNR>140 tab action[29]
..<SNR>140 reset to[5]
..<SNR>140 filter or send message[3] 
..<SNR>140_do_filter[4]
..97, line 2
Vim(call):E315: ml_get: invalid lnum: 4
```
<img width="874" alt="Bildschirmfoto 2020-08-14 um 20 38 39" src="https://user-images.githubusercontent.com/15885926/90282861-65ddeb00-de6f-11ea-9d9c-447ba52138cc.png">

(Selecting some of those naturally does nothing good).

This happens on MacOS and Windows using Vim.

Maybe this has something in common with #306 .

**Comment by liuchengxu** [comment]
As mentioned in #306, I'm a neovim user and I'm busy these days, so if you find any solution, feel free to PR, I may not spend more time on this.

**Comment by Grueslayer** [comment]
That's not good, if you stop supporting vim, i am also out of your plugin. I will be always on the stable vim side as long as Bram is keeping going on.

**Comment by liuchengxu** [comment]
Hmm, I'm not saying I won't support vim. As long as I still maintain this plugin, I'll try my best to support vim as well.

But you have to understand that since I'm a daily neovim and Linux/macOS user,  this plugin works better inevitably with neovim. You can see there are some subtle vim specific issues often reported by the users instead of myself, if people report these issues, I'll absolutely look into them when I get some time. People can get some solid responses quickly when I'm not busy, but have to wait if I don't have much time for these open source projects :(.

Furthermore, there are also serveral more nice features I want to have in this plugin, if someone can help resolve the vim/windows issues, we can definitely expect a nicer vim-clap. Looks like you are capable of this, I'm more than happy to invite you as a  collaborator to help me fix these kinds of problems if you do not mind, which will hopefully improve the vim support of this plugin I believe.

**Comment by liuchengxu** [comment]
#504 should also fix this issue.

**Comment by Grueslayer** [comment]
#504 didn't fixed it for me.

**Comment by liuchengxu** [comment]
I can no longer reproduce with that patch. Have you recompiled the Rust binary locally?

**Comment by liuchengxu** [comment]
That won't work as the Rust source file has been changed and you need to recompile, or you need to wait for the next release.
