### ISSUE TITLE
Snippet support comparable to fzf.vim

### ISSUE THREAD

**Issue by kanmii** [liuchengxu/vim-clap#664]
It will be nice to have a `:Clap snippets` provider just like fzf.vim.

**Comment by romgrk** [comment]
For which snippet provider? For most use cases, it's fairly simple to add your own provider, for example I use the following declaration to implement a provider for my session files:

```vim
let clap_provider_session = {
\ 'source': {-> xolox#session#complete_names('', 'OpenSession ', 0)},
\ 'sink': 'OpenSession',
\}
```

**Comment by kanmii** [comment]
Oh thanks. I will take a stab at writing a provider. Fzf uses ultisnips.

**Comment by aMOPel** [comment]
@romgrk @kanmii 
Hi there,
I actually did a little implementation, maybe you wanna put it with the examples for custom providers, since there arent many yet.

Main problem was to get the snippets for the current buffer, because clap counts, you would just get the snippets for the clap window. I tried to use the on_enter key but it just didnt work for me, so this implementation ended up a little ugly, because it needs a global variable and an autocommand. Im not really experienced with vimscript so that was the best i could do.

```
" eval(string('\' . g:UltiSnipsExpandTrigger)) --> tried to use the custom set trigger but couldnt figure it out
let g:clap_provider_snippets = {
  \'source': g:MySnippetsTemp, --> list of snippets with evenly spaced descriptions, made on bufenter but not in a clap window
  \'source_type': 2,
  \'sink': { snippet -> execute("norm a" . substitute(snippet, '\s\+.*$', '\t', ""))}, --> substitute the details with a single tab to expand the snippet ( doesnt work if tab isnt the expand key)
  \'description': 'search snippets'
  \}
```


```
function! s:MyGetAllSnippets() abort
  let maxlen = 0
  let pairs = []
  call UltiSnips#SnippetsInCurrentScope(1) --> put current snippets in g:current_ulti_dict
  for [k, v] in items(g:current_ulti_dict) --> the rest is code to evenly space the details for the snippets out, stolen from your maps provider
    let maxlen = max([maxlen, len(k)])
    call add(pairs, [k, substitute(v, '^\*\?[@ ]\?', '', '')])
  endfor
  let maxlen = min([maxlen, 35])
  let g:MySnippetsTemp = map(pairs, "printf('%-'.maxlen.'s', v:val[0]).' '.v:val[1]")
endfunction

--> needed to build smth that keeps the snippets from the current buffer and not the clap window
augroup MyAutoCmd
  autocmd!
  autocmd BufEnter * if &ft != "clap_input" |
   \ call s:MyGetAllSnippets() |
   \ endif 
augroup END
```
![Peek 2021-04-26 14-08](https://user-images.githubusercontent.com/36712072/116080101-f0cae280-a698-11eb-90c3-3c463fc7871a.gif)

also i thought it would be really nice to have a "details" key or smth where you can pass in another list, which is parallel to the source list and that is formated to serve as details for the items in the clap search window. sorta like the thing you did with the maps provider, where there is a mapping, and then evenly spaced out where it is mapped to. alternative would be to accept a dict in the source key, where keys are the items and values their details/descriptions. and then ideally the details would not be dumped into the sink key, so there is no need to filter them out like i did.

**Comment by romgrk** [comment]
I worry that this implementation is a bit too brittle to put as an example. Have you tried opening an issue with UltiSnips to ask them the best way to implement this? I also wonder if such implementation wouldn't be better placed within the UltiSnips repo.

**Comment by liuchengxu** [comment]
https://github.com/liuchengxu/vim-clap/wiki/Examples might also be a good place for such an example, which is not guaranteed to be bug-free anyway.
