### ISSUE TITLE
Add ability to pass dir option from :Clap providers  to grep, files, etc.

### ISSUE THREAD

**Issue by sudoerwx** [liuchengxu/vim-clap#730]
**Is your feature request related to a problem? Please describe.**
It's not a problem but it seems to be a good option to add  in order to make one map instead of many just because i use dir specific commands

**Describe the solution you'd like**
Just to add the DIR option as a second argument of :Clap providers and pass it to all providers that can use it

**Describe alternatives you've considered**
No alternative  solutions, now I just use multiply mappings and pass dir param to each
Or can add some kind of integration with coc-explorer and/or nerd-tree

**Additional context**
I use these mappings with dir param to implement dir limited search from coc-explorer, its super useful feature for every day development in vim

**Comment by liuchengxu** [comment]
Things are changed a lot since this issue, e.g., now we can `:Clap igrep` for example where you can navigate the directories like `filer` and then do the grep work under the switched directory. Feel free to try the latest version if it still matters and let me know if it still lacks the feature you are looking for, closing for now.
