### ISSUE TITLE
Edit files directly in the preview window

### ISSUE THREAD

**Issue by f0s3** [liuchengxu/vim-clap#860]
I would like to have an ability to edit files directly in the preview window. Similarly to what jetbrains IDEs have (ctrl+shift+f).

**Comment by liuchengxu** [comment]
There are a few limitations:

- Not every provider's preview is a file.
- Only doable for NeoVim as Vim popup is not focusable.
- The preview now is not loading the entire file but the necessary lines, in order to edit in the preview window without introducing much complexity, it's straightforward to load the entire file into the preview buffer, and then you move into the preview window to modify it.

The alternative workflow is to select the items and open the quickfix to do the operations there.
