### ISSUE TITLE
Key bindings are not consistent across all providers

### ISSUE THREAD

**Issue by luisdavim** [liuchengxu/vim-clap#864]
_Instructions: Replace the template text and remove irrelevant text (including this line)_
**Warning: if you don't fill this issue template and provide the reproducible steps the issue could be closed directly.**

**Environment (please complete the following information):**
 - OS: macOS
 - (Neo)Vim version: NVIM v0.7.2
 - vim-clap version: latest
 - Have you reproduced with a minimal vimrc: yes
 - Have you updated to the latest plugin version: yes
 - Have you upgraded to/compiled the latest Rust binary: yes

**Describe the bug**

With some providers I can use <kbd>Ctrl</kbd> + <kbd>v</kbd>; <kbd>Ctrl</kbd> + <kbd>x</kbd>; <kbd>Ctrl</kbd> + <kbd>t</kbd> to open a split or tab, but this doesn't work for all providers.
For example, it works with `files` but not `filler`, it works with `grep2` but not with `coc_outline` or `coc_diagnostics` or when using `Clap` with `coc-references`...

**Comment by liuchengxu** [comment]
Thanks for the question, this's unfortunately expected behavior for now, for clap currently only provides a default implementation for the providers whose item is file-like and the provider needs to state it explicitly (https://github.com/liuchengxu/vim-clap/blob/8e47e5b8ab/autoload/clap/provider/grep2.vim), which is not extensible.

I can imagine it can be improved in such a way that defining generic key binding traits each provider can implement on its own. However, still, not all the providers can support Ctrl-c/x/t at the end of the day as not all items make sense to be opened in a split or tab.
